// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file flycam.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _flycam_H_
#define _flycam_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdint.h>
#include <stdbool.h>

/*!
 * @brief This struct represents the structure UPDATE defined by the user in the IDL file.
 * @ingroup flycam
 */
typedef struct UPDATE
{
    int32_t id;
} UPDATE;

struct ucdrBuffer;

bool UPDATE_serialize_topic(struct ucdrBuffer* writer, const UPDATE* topic);
bool UPDATE_deserialize_topic(struct ucdrBuffer* reader, UPDATE* topic);
uint32_t UPDATE_size_of_topic(const UPDATE* topic, uint32_t size);

/*!
 * @brief This struct represents the structure CAM defined by the user in the IDL file.
 * @ingroup flycam
 */
typedef struct CAM
{
    int32_t id;
} CAM;

struct ucdrBuffer;

bool CAM_serialize_topic(struct ucdrBuffer* writer, const CAM* topic);
bool CAM_deserialize_topic(struct ucdrBuffer* reader, CAM* topic);
uint32_t CAM_size_of_topic(const CAM* topic, uint32_t size);


#ifdef __cplusplus
}
#endif

#endif // _flycam_H_