// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file flycam.c
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#include "flycam.h"

#include <ucdr/microcdr.h>
#include <string.h>

bool UPDATE_serialize_topic(ucdrBuffer* writer, const UPDATE* topic)
{
    bool success = true;

        success &= ucdr_serialize_int32_t(writer, topic->id);
    return success && !writer->error;
}

bool UPDATE_deserialize_topic(ucdrBuffer* reader, UPDATE* topic)
{
    bool success = true;

        success &= ucdr_deserialize_int32_t(reader, &topic->id);
    return success && !reader->error;
}

uint32_t UPDATE_size_of_topic(const UPDATE* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

    return size - previousSize;
}

bool CAM_serialize_topic(ucdrBuffer* writer, const CAM* topic)
{
    bool success = true;

        success &= ucdr_serialize_int32_t(writer, topic->id);
    return success && !writer->error;
}

bool CAM_deserialize_topic(ucdrBuffer* reader, CAM* topic)
{
    bool success = true;

        success &= ucdr_deserialize_int32_t(reader, &topic->id);
    return success && !reader->error;
}

uint32_t CAM_size_of_topic(const CAM* topic, uint32_t size)
{
    uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

    return size - previousSize;
}
